# -*- coding: utf-8 -*-
"""FP_CP_dictoinary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15qO6yBe-sfg1uiRM34PW5SbLOJ-4yD9I
"""

import numpy as np
import matplotlib.pyplot as plt
import numpy as np
from scipy.linalg import solve
from numpy.polynomial.legendre import leggauss
import torch
from scipy.linalg import eigh
from scipy.linalg import solve

#@title Fine propagatos
# R,P_i rational functions and distinct real numbers C, for 2,3,4-stage LOBATTO IIIC schemes,
# 3-stage RDAU IIA, Backward Euler and SDIRK-22
#

def R_LobattoIIIC2(B):
    I = np.eye(B.shape[0])
    D = B @ B + 2*B + 2*I
    return 2*I @ solve(D, I)


def P1_LobattoIIIC2(B):
    I = np.eye(B.shape[0])
    D = B @ B + 2*B + 2*I
    return solve(D, I)


def P2_LobattoIIIC2(B):
    I = np.eye(B.shape[0])
    D = B @ B + 2*B + 2*I
    return (B + I) @ solve(D, I)


P_LobattoIIIC2 = [
    P1_LobattoIIIC2,
    P2_LobattoIIIC2
]

C_LobattoIIIC2 = [
    0.0,
    1.0
]



# ------------------------------------------------------------
# 3-stage Lobatto IIIC
# ------------------------------------------------------------

def R_LobattoIIIC3(B):
    I = np.eye(B.shape[0])

    D = (
        B @ B @ B
        + 6*(B @ B)
        + 18*B
        + 24*I
    )

    return (-6*B + 24*I) @ solve(D, I)


def P1_LobattoIIIC3(B):
    I = np.eye(B.shape[0])

    D = (
        B @ B @ B
        + 6*(B @ B)
        + 18*B
        + 24*I
    )

    return (4*I - B) @ solve(D, I)


def P2_LobattoIIIC3(B):
    I = np.eye(B.shape[0])

    D = (
        B @ B @ B
        + 6*(B @ B)
        + 18*B
        + 24*I
    )

    return (16*I + 4*B) @ solve(D, I)


def P3_LobattoIIIC3(B):
    I = np.eye(B.shape[0])

    D = (
        B @ B @ B
        + 6*(B @ B)
        + 18*B
        + 24*I
    )

    return (
        4*I
        + 3*B
        + B @ B
    ) @ solve(D, I)


P_LobattoIIIC3 = [
    P1_LobattoIIIC3,
    P2_LobattoIIIC3,
    P3_LobattoIIIC3
]

C_LobattoIIIC3 = [
    0.0,
    0.5,
    1.0
]



# ------------------------------------------------------------
# 4-stage Lobatto IIIC
# ------------------------------------------------------------

def R_LobattoIIIC4(B):
    I = np.eye(B.shape[0])

    B2 = B @ B
    B3 = B2 @ B
    B4 = B3 @ B

    D = (
        B4
        + 12*B3
        + 72*B2
        + 240*B
        + 360*I
    )

    return (
        12*B2
        - 120*B
        + 360*I
    ) @ solve(D, I)


def P1_LobattoIIIC4(B):
    I = np.eye(B.shape[0])

    B2 = B @ B
    B3 = B2 @ B
    B4 = B3 @ B

    D = (
        B4
        + 12*B3
        + 72*B2
        + 240*B
        + 360*I
    )

    return (
        B2
        - 10*B
        + 30*I
    ) @ solve(D, I)


def P2_LobattoIIIC4(B):
    I = np.eye(B.shape[0])
    sqrt5 = np.sqrt(5)

    B2 = B @ B
    B3 = B2 @ B
    B4 = B3 @ B

    D = (
        B4
        + 12*B3
        + 72*B2
        + 240*B
        + 360*I
    )

    numerator = (
        (5/2)*(1-sqrt5)*B2
        + (25 - 15*sqrt5)*B
        + 150*I
    )

    return numerator @ solve(D, I)


def P3_LobattoIIIC4(B):
    I = np.eye(B.shape[0])
    sqrt5 = np.sqrt(5)

    B2 = B @ B
    B3 = B2 @ B
    B4 = B3 @ B

    D = (
        B4
        + 12*B3
        + 72*B2
        + 240*B
        + 360*I
    )

    numerator = (
        (5/2)*(1+sqrt5)*B2
        + (25 + 15*sqrt5)*B
        + 150*I
    )

    return numerator @ solve(D, I)


def P4_LobattoIIIC4(B):
    I = np.eye(B.shape[0])

    B2 = B @ B
    B3 = B2 @ B
    B4 = B3 @ B

    D = (
        B4
        + 12*B3
        + 72*B2
        + 240*B
        + 360*I
    )

    return (
        B3
        + 6*B2
        + 20*B
        + 30*I
    ) @ solve(D, I)


P_LobattoIIIC4 = [
    P1_LobattoIIIC4,
    P2_LobattoIIIC4,
    P3_LobattoIIIC4,
    P4_LobattoIIIC4
]

C_LobattoIIIC4 = [
    0.0,
    (5-np.sqrt(5))/10,
    (5+np.sqrt(5))/10,
    1.0
]



# ------------------------------------------------------------
# 3-stage Radau IIA
# ------------------------------------------------------------

def R_RadauIIA3(B):
    I = np.eye(B.shape[0])

    B2 = B @ B
    B3 = B2 @ B

    D = (
        B3
        + 9*B2
        + 36*B
        + 60*I
    )

    return (
        3*B2
        - 24*B
        + 60*I
    ) @ solve(D, I)


def P1_RadauIIA3(B):
    I = np.eye(B.shape[0])
    sqrt6 = np.sqrt(6)

    B2 = B @ B
    B3 = B2 @ B

    D = (
        B3
        + 9*B2
        + 36*B
        + 60*I
    )

    numerator = (
        (1 - 8*sqrt6/3)*B
        + (80/3 - 5*sqrt6/3)*I
    )

    return numerator @ solve(D, I)


def P2_RadauIIA3(B):
    I = np.eye(B.shape[0])
    sqrt6 = np.sqrt(6)

    B2 = B @ B
    B3 = B2 @ B

    D = (
        B3
        + 9*B2
        + 36*B
        + 60*I
    )

    numerator = (
        (1 + 8*sqrt6/3)*B
        + (80/3 + 5*sqrt6/3)*I
    )

    return numerator @ solve(D, I)


def P3_RadauIIA3(B):
    I = np.eye(B.shape[0])

    B2 = B @ B
    B3 = B2 @ B

    D = (
        B3
        + 9*B2
        + 36*B
        + 60*I
    )

    return (
        B2
        + 4*B
        + (20/3)*I
    ) @ solve(D, I)


P_RadauIIA3 = [
    P1_RadauIIA3,
    P2_RadauIIA3,
    P3_RadauIIA3
]

C_RadauIIA3 = [
    (4-np.sqrt(6))/10,
    (4+np.sqrt(6))/10,
    1.0
]



# ------------------------------------------------------------
# Backward Euler
# ------------------------------------------------------------

def R_BE(B):
    I = np.eye(B.shape[0])
    return solve(I + B, I)


P_BE = [R_BE]
C_BE = [1.0]

# ------------------------------------------------------------
# SDIRK-22
# ------------------------------------------------------------

gamma_SDIRK22 = (2.0 - np.sqrt(2.0)) / 2.0


def R_SDIRK22(B):
    I = np.eye(B.shape[0])
    Q = I + gamma_SDIRK22 * B

    return (I + (2.0 * gamma_SDIRK22 - 1.0) * B) @ solve(Q @ Q, I)


def P1_SDIRK22(B):
    I = np.eye(B.shape[0])
    Q = I + gamma_SDIRK22 * B

    return (1.0 - gamma_SDIRK22) * solve(Q @ Q, I)


def P2_SDIRK22(B):
    I = np.eye(B.shape[0])
    Q = I + gamma_SDIRK22 * B

    return gamma_SDIRK22 * solve(Q, I)


P_SDIRK22 = [
    P1_SDIRK22,
    P2_SDIRK22
]

C_SDIRK22 = [
    gamma_SDIRK22,
    1.0
]


# ------------------------------------------------------------
# Skalare Auswertung der Stabilitätsfunktion des
# 4-stage Lobatto IIIC Verfahrens für die Spektraldarstellung
# ------------------------------------------------------------

def R_LobattoIIIC4_scalar(s):
    s = np.asarray(s, dtype=np.float64)
    denominator = (((s + 12.0) * s + 72.0) * s + 240.0) * s + 360.0
    numerator = (12.0 * s - 120.0) * s + 360.0
    return numerator / denominator

# ------------------------------------------------------------
# Skalare Auswertung der Stabilitätsfunktion des
# 3-stage Radau IIA Verfahrens für die Spektraldarstellung
# ------------------------------------------------------------

def R_RadauIIA3_scalar(s):
    s = np.asarray(s, dtype=np.float64)

    numerator = (3.0 * s - 24.0) * s + 60.0
    denominator = ((s + 9.0) * s + 36.0) * s + 60.0

    return numerator / denominator

#@title FP call
# Ditionary to easily call different FP´s and CP´s when using the parareal-algorithm

FP = {
    "LobattoIIIC2": {
        "R": R_LobattoIIIC2,
        "P": P_LobattoIIIC2,
        "C": C_LobattoIIIC2,
        "title": "two-stage Lobatto IIIC"
    },

    "LobattoIIIC3": {
        "R": R_LobattoIIIC3,
        "P": P_LobattoIIIC3,
        "C": C_LobattoIIIC3,
        "title": "three-stage Lobatto IIIC"
    },

    "LobattoIIIC4": {
        "R": R_LobattoIIIC4,
        "P": P_LobattoIIIC4,
        "C": C_LobattoIIIC4,
        "R_scalar": R_LobattoIIIC4_scalar,
        "title": "four-stage Lobatto IIIC"
    },

    "RadauIIA3": {
        "R": R_RadauIIA3,
        "P": P_RadauIIA3,
        "C": C_RadauIIA3,
        "R_scalar": R_RadauIIA3_scalar,
        "title": "three-stage Radau IIA"
    },

    "BackwardEuler": {
        "R": R_BE,
        "P": P_BE,
        "C": C_BE,
        "title": "Backward Euler"
    },

    "SDIRK22": {
        "R": R_SDIRK22,
        "P": P_SDIRK22,
        "C": C_SDIRK22,
        "title": "SDIRK-22"
    }
}

SDIRK22 = FP["SDIRK22"]
BE = FP["BackwardEuler"]